apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyter
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - image: jupyter:3
        name: jupyter
        volumeMounts:
        - mountPath: /notebooks
          name: notebooks-volume
      volumes:
      - name: notebooks-volume
        persistentVolumeClaim:
          claimName: notebooks-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter
  name: jupyter
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-folder
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /run/desktop/mnt/host/wsl/c/temp/jupyter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebooks-pv-claim
spec:
  storageClassName: local-folder
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi