apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyter
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - image: jupyter:3
        name: jupyter
        volumeMounts:
        - mountPath: /notebooks
          name: notebooks-volume
      volumes:
      - name: notebooks-volume
        hostPath:
          path: /run/desktop/mnt/host/wsl/c/temp/jupyter
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter
  name: jupyter
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter
  type: LoadBalancer
